### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by iparask**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by iparask** [comment]
@conda-forge-admin please rerender

**Comment by andre-merzky** [comment]
I am afraid tests fail here also :-/

**Comment by mtitov** [comment]
@iparask can you please update url here as in RS, and requirements
```
    - radical.utils >=1.60
    - radical.pilot >=1.60
```

**Comment by mtitov** [comment]
close in favor #69

**Pull request closed without merging**
